module ProjTagStudyCharacteristics
  class EliminatedTerm

    def self.terms
      {'mental health' =>
        ['alcohol amnestic disorder',
        'aids dementia complex',
        'alcohol withdrawal delirium',
        'alcohol-related disorders',
        'alcoholic intoxication',
        'alcoholism',
        'alzheimer disease',
        'amnesia',
        'amnesia, anterograde',
        'amnesia, retrograde',
        'amnesia, transient global',
        'amphetamine-related disorders',
        'animal assisted therapy',
        'appetite',
        'aromatherapy',
        'arousal',
        'art therapy',
        'autogenic training',
        'autosuggestion',
        'behavior control',
        'bibliotherapy',
        'biofeedback, psychology',
        'bisexuality',
        'cataplexy',
        'catatonia',
        'child guidance',
        'cocaine-related disorders',
        'coitus',
        'coitus interruptus',
        'color therapy',
        'consciousness disorders',
        'coprophagia',
        'creativeness',
        'dance therapy',
        'delirium',
        'dementia',
        'dementia, multi-infarct',
        'dementia, vascular',
        'depression, postpartum',
        'disorders of excessive somnolence',
        'diurnal enuresis',
        'dyssomnias',
        'electroshock',
        'encopresis',
        'enuresis',
        'equine-assisted therapy',
        'feedback, psychological',
        'feedback, sensory',
        'field dependence-independence',
        'freezing reaction, cataleptic',
        'galvanic skin response',
        'habituation, psychophysiologic',
        'hallucinations',
        'heroin dependence',
        'heterosexuality',
        'higher nervous activity',
        'homosexuality',
        'homosexuality, female',
        'homosexuality, male',
        'hypersomnolence, idiopathic',
        'hypnosis',
        'illusions',
        'imagery (psychotherapy)',
        'intention',
        'intergenerational relations',
        'introversion (psychology)',
        'jet lag syndrome',
        'kleine-levin syndrome',
        'korsakoff syndrome',
        'learning',
        'lethargy',
        'marijuana abuse',
        'meditation',
        'memory disorders',
        'mental fatigue',
        'mental retardation',
        'mind-body relations (metaphysics)',
        'morphine dependence',
        'music therapy',
        'mutism',
        'narcolepsy',
        'neonatal abstinence syndrome',
        'neurolinguistic programming',
        'night terrors',
        'nocturnal enuresis',
        'nocturnal paroxysmal dystonia',
        'opioid-related disorders',
        'orthomolecular therapy',
        'pain',
        'pain threshold',
        'parapsychology',
        'parasomnias',
        'pattern recognition, visual',
        'phencyclidine abuse',
        'play therapy',
        'pleasure',
        'psychodrama',
        'psycholinguistics',
        'psychology, social',
        'psychomotor agitation',
        'psychophysiology',
        'psychoses, alcoholic',
        'psychoses, substance-induced',
        'psychosurgery',
        'reaction time',
        'relaxation therapy',
        'rem sleep behavior disorder',
        'rem sleep parasomnias',
        'restless legs syndrome',
        'rett syndrome',
        'role playing',
        'self mutilation',
        'sensitivity training groups',
        'sex differentiation disorders',
        'sexuality',
        'signal detection, psychological',
        'sleep',
        'sleep arousal disorders',
        'sleep bruxism',
        'sleep deprivation',
        'sleep disorders',
        'sleep disorders, circadian rhythm',
        'sleep disorders, intrinsic',
        'sleep initiation and maintenance disorders',
        'sleep paralysis',
        'sleep stages',
        'sleep-wake transition disorders',
        'sleep, rem',
        'somnambulism',
        'startle reaction',
        'stereognosis',
        'substance abuse, intravenous',
        'substance withdrawal syndrome',
        'substance-related disorders',
        'suggestion',
        'tic disorders',
        'tobacco use disorder',
        'tourette syndrome',
        'uncertainty',
        'wakefulness',
        'wernicke encephalopathy'],

      'oncology' => ['adenoma, islet cell',
        'adenoma, liver cell',
        'anal gland neoplasms',
        'anaplasia',
        'anemia, myelophthisic',
        'anemia, refractory',
        'anemia, refractory, with excess of blasts',
        'anemia, sideroblastic',
        'apudoma',
        'basal cell nevus syndrome',
        'blast crisis',
        'bone marrow neoplasms',
        'carcinoid heart disease',
        'carcinoma 256, walker',
        'carcinoma, krebs 2',
        'carcinosarcoma',
        'carney complex',
        'cell transformation, neoplastic',
        'cell transformation, viral',
        'cerebral ventricle neoplasms',
        'choroid plexus neoplasms',
        'cocarcinogenesis',
        'colorectal neoplasms, hereditary nonpolyposis',
        'dendritic cell sarcoma, follicular',
        'dendritic cell sarcoma, interdigitating',
        'denys-drash syndrome',
        'epstein-barr virus infections',
        'esthesioneuroblastoma, olfactory',
        'exostoses, multiple hereditary',
        'gardner syndrome',
        'genes, recessive',
        'hamartoma syndrome, multiple',
        'hemoglobinuria, paroxysmal',
        'histiocytic disorders, malignant',
        'histiocytic sarcoma',
        'immunoproliferative small intestinal disease',
        'insulinoma',
        'keratosis, actinic',
        'lambert-eaton myasthenic syndrome',
        'langerhans cell sarcoma',
        'leukemia, radiation-induced',
        'leukemic infiltration',
        'leukemoid reaction',
        'leukoplakia',
        'leukoplakia, hairy',
        'leukoplakia, oral',
        'li-fraumeni syndrome',
        'limbic encephalitis',
        'liver neoplasms, experimental',
        'luteoma',
        'lymphangioleiomyomatosis',
        'lymphangiomyoma',
        'lymphatic metastasis',
        'lymphoproliferative disorders',
        'mastocytoma',
        'mastocytoma, skin',
        'maxillary diseases',
        'meigs syndrome',
        'melanoma, experimental',
        'monoclonal gammopathy of undetermined significance',
        'muir-torre syndrome',
        'myelitis, transverse',
        'neoplasm invasiveness',
        'neoplasm metastasis',
        'neoplasm recurrence, local',
        'neoplasm regression, spontaneous',
        'neoplasm seeding',
        'neoplasm, residual',
        'neoplasms, connective tissue',
        'neoplasms, experimental',
        'neoplasms, radiation-induced',
        'neoplasms, unknown primary',
        'neoplastic cells, circulating',
        'neoplastic processes',
        'neurocytoma',
        'opsoclonus-myoclonus syndrome',
        'papilloma, choroid plexus',
        'paraproteinemias',
        'peritoneal neoplasms',
        'peutz-jeghers syndrome',
        'pinealoma',
        'pituitary neoplasms',
        'poems syndrome',
        'pregnancy complications, neoplastic',
        'pulmonary adenomatosis, ovine',
        'pulmonary sclerosing hemangioma',
        'sebaceous gland neoplasms',
        'sezary syndrome',
        'solitary fibrous tumor, pleural',
        'spinal neoplasms',
        'thyroid neoplasms',
        'thyroid nodule',
        'trophoblastic neoplasms',
        'tumor lysis syndrome',
        'tumor virus infections',
        'uterine cervical dysplasia',
        'vestibulocochlear nerve diseases',
        'wagr syndrome',
        'waldenstrom macroglobulinemia',
        'xeroderma pigmentosum',
        ],

        'cardiovascular' => ['alagille syndrome',
        'aneurysm, infected',
        'angiography, digital subtraction',
        'angioscopes',
        'angioscopy',
        'aortic rupture',
        'aortitis',
        'arterio-arterial fistula',
        'arteriovenous fistula',
        'arteriovenous malformations',
        'balloon occlusion',
        'baroreflex',
        'barth syndrome',
        'blood flow velocity',
        'blood gas monitoring, transcutaneous',
        'body surface potential mapping',
        'brugada syndrome',
        'cardiography, impedance',
        'cardiomyopathy, alcoholic',
        'cardiomyopathy, hypertrophic, familial',
        'cardiotocography',
        'carney complex',
        'carotid artery, internal, dissection',
        'central nervous system vascular malformations',
        'central nervous system venous angioma',
        'cineangiography',
        'defibrillators, implantable',
        'dyspnea',
        'dyspnea, paroxysmal',
        'echo-planar imaging',
        'echocardiography, doppler, pulsed',
        'embolism, amniotic fluid',
        'exercise test',
        'extracorporeal membrane oxygenation',
        'fluorescein angiography',
        'fontan procedure',
        'glycogen storage disease type iib',
        'heart-lung transplantation',
        'hemangioma, cavernous, central nervous system',
        'hypotension, orthostatic',
        'intermittent claudication',
        'intracranial aneurysm',
        'intracranial arteriovenous malformations',
        'kartagener syndrome',
        'kearns-sayre syndrome',
        'laser-doppler flowmetry',
        'leopard syndrome',
        'leriche syndrome',
        'loeys-dietz syndrome',
        'magnetic resonance imaging, cine',
        'marfan syndrome',
        'mediastinoscopy',
        'myoelectric complex, migrating',
        'oximetry',
        'pericardial window techniques',
        'pericardiocentesis',
        'persistent fetal circulation syndrome',
        'pregnancy complications, cardiovascular',
        'primary graft dysfunction',
        'pulmonary circulation',
        'pulsatile flow',
        'renal circulation',
        'shy-drager syndrome',
        'sinus pericranii',
        'takayasu arteritis',
        'valsalva maneuver',
        'vascular fistula',
        'vein of galen malformations',
        'vertebral artery dissection',
        'williams syndrome']
       }

    end

  end
end
